package com.lsdd.dao;

import com.lsdd.entity.Permission;

import java.util.List;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    Permission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int updateByPrimaryKey(Permission record);


    Permission getByName(String permissionName);

    List<Permission> selectListPermission();
}