package com.lsdd.dao;

import com.lsdd.entity.RolePermission;

import java.util.List;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    RolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permissions
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int updateByPrimaryKey(RolePermission record);

    List<RolePermission> selectByRoleId(Long id);
}