package com.lsdd.dao;

import com.lsdd.entity.User;
import com.lsdd.entity.UserRoleVO;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    int updateByPrimaryKey(User record);

    User getByName(String userName);

    List<User> selectListUser();

    List<User> selectListUserRoleVO();

    User selectUserRoleVO(Long id);
}