package com.lsdd.entity;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.permission
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.description
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.rid
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private Long rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permissions.available
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private Boolean available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.id
     *
     * @return the value of sys_permissions.id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.id
     *
     * @param id the value for sys_permissions.id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.permission
     *
     * @return the value of sys_permissions.permission
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.permission
     *
     * @param permission the value for sys_permissions.permission
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.description
     *
     * @return the value of sys_permissions.description
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.description
     *
     * @param description the value for sys_permissions.description
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.rid
     *
     * @return the value of sys_permissions.rid
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.rid
     *
     * @param rid the value for sys_permissions.rid
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permissions.available
     *
     * @return the value of sys_permissions.available
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permissions.available
     *
     * @param available the value for sys_permissions.available
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }
}