package com.lsdd.entity;

import org.springframework.beans.factory.annotation.Autowired;

import java.util.HashSet;
import java.util.Set;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.role
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.description
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.pid
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private Long pid;


    public Role getpRole() {
        return pRole;
    }

    public Role setpRole(Role pRole) {
        this.pRole = pRole;
        return this;
    }

    private Role pRole;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.available
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     * 是否锁定
     */
    private Boolean available;


    private Set<Permission> permissionSet = new HashSet<>();

    public Set<Permission> getPermissionSet() {
        return permissionSet;
    }

    public Role setPermissionSet(Set<Permission> permissionSet) {
        this.permissionSet = permissionSet;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.id
     *
     * @return the value of sys_roles.id
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.id
     *
     * @param id the value for sys_roles.id
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.role
     *
     * @return the value of sys_roles.role
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.role
     *
     * @param role the value for sys_roles.role
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.description
     *
     * @return the value of sys_roles.description
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.description
     *
     * @param description the value for sys_roles.description
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.pid
     *
     * @return the value of sys_roles.pid
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.pid
     *
     * @param pid the value for sys_roles.pid
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.available
     *
     * @return the value of sys_roles.available
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.available
     *
     * @param available the value for sys_roles.available
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    @Override
    public String toString() {
        return "Role{" +
                "id=" + id +
                ", role='" + role + '\'' +
                ", description='" + description + '\'' +
                ", pid=" + pid +
                ", pRole=" + pRole +
                ", available=" + available +
                ", permissionSet=" + permissionSet +
                '}';
    }
}