package com.lsdd.entity;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users_roles.id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users_roles.user_id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users_roles.role_id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.id
     *
     * @return the value of sys_users_roles.id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.id
     *
     * @param id the value for sys_users_roles.id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.user_id
     *
     * @return the value of sys_users_roles.user_id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.user_id
     *
     * @param userId the value for sys_users_roles.user_id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.role_id
     *
     * @return the value of sys_users_roles.role_id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.role_id
     *
     * @param roleId the value for sys_users_roles.role_id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}