package com.lsdd.entity;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.HashSet;
import java.util.Set;


public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.username
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    @NotNull(message = "用户名不能为空")
    @Size(min = 3, max = 20, message = "用户名长度必须是3-11个字符")
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.password
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    @NotNull(message = "密码不能为空")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.salt
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.role_id
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users.locked
     *
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    private Boolean locked;

    private Set<Role> roleSet = new HashSet<>();

    public Set<Role> getRoleSet() {
        return roleSet;
    }

    public User setRoleSet(Set<Role> roleSet) {
        this.roleSet = roleSet;
        return this;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.id
     *
     * @return the value of sys_users.id
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.id
     *
     * @param id the value for sys_users.id
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.username
     *
     * @return the value of sys_users.username
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.username
     *
     * @param username the value for sys_users.username
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.password
     *
     * @return the value of sys_users.password
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.password
     *
     * @param password the value for sys_users.password
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.salt
     *
     * @return the value of sys_users.salt
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.salt
     *
     * @param salt the value for sys_users.salt
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.role_id
     *
     * @return the value of sys_users.role_id
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.role_id
     *
     * @param roleId the value for sys_users.role_id
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users.locked
     *
     * @return the value of sys_users.locked
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public Boolean getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users.locked
     *
     * @param locked the value for sys_users.locked
     * @mbg.generated Thu Jun 25 20:21:33 CST 2020
     */
    public void setLocked(Boolean locked) {
        this.locked = locked;
    }


    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", salt='" + salt + '\'' +
                ", roleId='" + roleId + '\'' +
                ", locked=" + locked +
                '}';
    }
}